import Link from 'next/link';
import {notFound} from 'next/navigation';
import {MessageCircle,LifeBuoy,Store,CalendarDays,MapPin,FileText,Check} from 'lucide-react';
import {db} from '@/lib/db';
import {Header} from '@/components/Header';
import {rupiah} from '@/lib/money';
import {requireCustomer} from '@/lib/customer-auth';
import {canCustomerCancel,customerStatusLabel,statusTone} from '@/lib/customer-ui';

export const dynamic='force-dynamic';export const metadata={title:'Detail Pesanan | JasaBatam',robots:{index:false,follow:false}};
function addressText(value:unknown){if(!value||typeof value!=='object'||Array.isArray(value))return '-';const v=value as Record<string,unknown>;return [v.line1,v.area].filter(x=>typeof x==='string'&&x).join(', ')||'-'}
export default async function Page({params}:{params:Promise<{id:string}>}){
  const {id}=await params,auth=await requireCustomer(`/pesanan/${id}`);
  const o=await db.order.findFirst({where:{publicId:id,customerId:auth.customer.id},include:{items:true,area:true,history:{orderBy:{createdAt:'asc'}},partner:{select:{businessName:true,media:{where:{hidden:false,kind:{in:['LOGO','PROFILE']}},orderBy:{sortOrder:'asc'},take:1,select:{url:true}}}},thread:{select:{id:true}}}});if(!o)notFound();
  return <><Header/><main className="order-detail-page"><div className="container"><Link className="detail-back" href="/pesanan">‹ Kembali</Link><div className="order-detail-heading"><div><h1>Order #{o.publicId}</h1><p>{o.createdAt.toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'})}</p></div><span className={`customer-badge ${statusTone(o.status)}`}>{customerStatusLabel[o.status]}</span></div><div className="order-detail-grid"><section className="order-detail-left"><div className="detail-section card"><h2>Tracking Pesanan</h2><div className="tracking-timeline">{o.history.map((h,i)=><div className="tracking-row" key={h.id}><span className="tracking-dot done"><Check size={13}/></span><div><b>{customerStatusLabel[h.newStatus]}</b><small>{h.createdAt.toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'})}</small>{h.reason&&<p>{h.reason}</p>}</div>{i<o.history.length-1&&<i/>}</div>)}</div></div><div className="detail-section card"><h2>Informasi Layanan</h2><div className="service-partner"><div className="order-partner-logo">{o.partner?.media[0]?.url?<img src={o.partner.media[0].url} alt=""/>:<Store/>}</div><div><b>{o.partner?.businessName||'Mitra belum ditetapkan'}</b>{o.items.map(item=><span key={item.id}>{item.name} · {item.quantity} × {rupiah(item.unitPrice)} <strong>{rupiah(item.lineTotal)}</strong></span>)}</div></div><dl className="order-info-list"><div><dt><CalendarDays/> Jadwal</dt><dd>{o.scheduledAt.toLocaleString('id-ID',{dateStyle:'full',timeStyle:'short',timeZone:'Asia/Jakarta'})}</dd></div><div><dt><MapPin/> Alamat</dt><dd>{addressText(o.addressSnapshot)}</dd></div><div><dt><FileText/> Catatan</dt><dd>{o.customerNote||'Tidak ada catatan.'}</dd></div></dl></div></section><aside className="order-cost card"><h2>Ringkasan Biaya</h2><dl><div><dt>Subtotal</dt><dd>{rupiah(o.subtotal)}</dd></div>{o.discount>0&&<div><dt>Diskon</dt><dd>-{rupiah(o.discount)}</dd></div>}{o.paymentFee>0&&<div><dt>Biaya pembayaran</dt><dd>{rupiah(o.paymentFee)}</dd></div>}{o.areaSurcharge>0&&<div><dt>Biaya area</dt><dd>{rupiah(o.areaSurcharge)}</dd></div>}<div className="cost-total"><dt>Total</dt><dd>{rupiah(o.total)}</dd></div></dl>{o.thread&&o.partnerId&&<Link className="btn primary detail-action" href={`/chat?order=${encodeURIComponent(o.publicId)}`}><MessageCircle/> Chat Mitra</Link>}<Link className="btn outline detail-action" href="/akun#bantuan"><LifeBuoy/> Hubungi Bantuan</Link>{canCustomerCancel(o.status)&&<form action={`/api/customer/orders/${o.publicId}/cancel`} method="post"><button className="btn danger detail-action" type="submit">Batalkan Pesanan</button></form>}</aside></div></div></main></>
}
