'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,MessageCircle,Search,Send,Store} from 'lucide-react';

type Role='CUSTOMER'|'PARTNER'|'ADMIN'|'SYSTEM';
type Conversation={orderId:string;status:string;partnerName:string;partnerLogo:string|null;lastMessage:string;lastMessageAt:string|null;lastRole:Role|null;readAt:string|null};
type Message={id:string;role:Role;body:string|null;createdAt:string};
const labels:Record<string,string>={NEW:'Pesanan Dibuat',SEARCHING_PARTNER:'Mencari Mitra',OFFERED:'Menunggu Konfirmasi Mitra',ACCEPTED:'Pesanan Diterima',ON_THE_WAY:'Mitra Menuju Lokasi',ARRIVED:'Mitra Tiba',IN_PROGRESS:'Sedang Dikerjakan',COMPLETED:'Selesai',CANCELLED:'Dibatalkan',DISPUTED:'Dalam Penanganan',REFUND_PENDING:'Refund Diproses',REFUNDED:'Refund Selesai'};
function time(v:string|null){if(!v)return '';return new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit'}).format(new Date(v))}
export function ChatClient({baseApi,myRole,initialOrder,customerMode=true}:{baseApi:string;myRole:'CUSTOMER'|'PARTNER';initialOrder?:string;customerMode?:boolean}){
  const [conversations,setConversations]=useState<Conversation[]>([]),[selected,setSelected]=useState(initialOrder||''),[messages,setMessages]=useState<Message[]>([]),[status,setStatus]=useState(''),[query,setQuery]=useState(''),[text,setText]=useState(''),[sending,setSending]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[hasOlder,setHasOlder]=useState(false),[loadingOlder,setLoadingOlder]=useState(false);
  const latestRef=useRef('');const endRef=useRef<HTMLDivElement>(null);
  const loadConversations=useCallback(async(signal?:AbortSignal)=>{const r=await fetch(baseApi,{cache:'no-store',signal});if(!r.ok)throw new Error('LOAD_FAILED');const j=await r.json();setConversations(j.conversations||[]);setLoading(false);if(!selected&&j.conversations?.length)setSelected(j.conversations[0].orderId)},[baseApi,selected]);
  const loadInitial=useCallback(async(orderId:string,signal?:AbortSignal)=>{const r=await fetch(`${baseApi}/${encodeURIComponent(orderId)}/messages`,{cache:'no-store',signal});if(!r.ok)throw new Error('LOAD_FAILED');const j=await r.json();const rows:Message[]=j.messages||[];setMessages(rows);setHasOlder(Boolean(j.hasOlder));setStatus(j.status||'');latestRef.current=rows.at(-1)?.id||'';void fetch(`${baseApi}/${encodeURIComponent(orderId)}/read`,{method:'POST'}).catch(()=>{});requestAnimationFrame(()=>endRef.current?.scrollIntoView({block:'end'}))},[baseApi]);
  useEffect(()=>{const controller=new AbortController();loadConversations(controller.signal).catch(()=>{if(!controller.signal.aborted){setError('Percakapan belum dapat dimuat.');setLoading(false)}});return()=>controller.abort()},[loadConversations]);
  useEffect(()=>{if(!selected){setMessages([]);return}const controller=new AbortController();setError('');loadInitial(selected,controller.signal).catch(()=>{if(!controller.signal.aborted)setError('Pesan belum dapat dimuat.')});return()=>controller.abort()},[selected,loadInitial]);
  useEffect(()=>{if(!selected)return;let stopped=false,timer:number|undefined,active:AbortController|undefined;const poll=async()=>{active=new AbortController();try{const after=latestRef.current?`?after=${encodeURIComponent(latestRef.current)}`:'';const r=await fetch(`${baseApi}/${encodeURIComponent(selected)}/messages${after}`,{cache:'no-store',signal:active.signal});if(r.ok){const j=await r.json();const incoming:Message[]=j.messages||[];if(incoming.length){setMessages(prev=>{const seen=new Set(prev.map(x=>x.id));return [...prev,...incoming.filter(x=>!seen.has(x.id))]});latestRef.current=incoming.at(-1)?.id||latestRef.current;void fetch(`${baseApi}/${encodeURIComponent(selected)}/read`,{method:'POST'}).catch(()=>{});requestAnimationFrame(()=>endRef.current?.scrollIntoView({block:'end'}))}setStatus(j.status||status)}}catch{}finally{if(!stopped)timer=window.setTimeout(poll,3000)}};timer=window.setTimeout(poll,3000);return()=>{stopped=true;if(timer)clearTimeout(timer);active?.abort()}},[baseApi,selected,status]);
  async function loadOlder(){if(!selected||loadingOlder||!messages.length||!hasOlder)return;setLoadingOlder(true);try{const r=await fetch(`${baseApi}/${encodeURIComponent(selected)}/messages?before=${encodeURIComponent(messages[0].id)}`,{cache:'no-store'});if(!r.ok)return;const j=await r.json();const older:Message[]=j.messages||[];setMessages(prev=>{const seen=new Set(prev.map(x=>x.id));return [...older.filter(x=>!seen.has(x.id)),...prev]});setHasOlder(Boolean(j.hasOlder))}finally{setLoadingOlder(false)}}
  async function send(e:React.FormEvent){e.preventDefault();const body=text.trim();if(!body||sending||!selected)return;setSending(true);setError('');try{const r=await fetch(`${baseApi}/${encodeURIComponent(selected)}/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({body})});const j=await r.json().catch(()=>({}));if(!r.ok){setError(j.message||'Pesan gagal dikirim.');return}const m=j.message as Message;setMessages(prev=>prev.some(x=>x.id===m.id)?prev:[...prev,m]);latestRef.current=m.id;setText('');void loadConversations().catch(()=>{});requestAnimationFrame(()=>endRef.current?.scrollIntoView({block:'end'}))}catch{setError('Koneksi bermasalah. Pesan belum terkirim.')}finally{setSending(false)}}
  const current=conversations.find(x=>x.orderId===selected);const filtered=useMemo(()=>conversations.filter(c=>`${c.partnerName} ${c.orderId}`.toLowerCase().includes(query.toLowerCase())),[conversations,query]);
  if(!loading&&!conversations.length)return <div className="chat-empty card"><MessageCircle/><h2>Belum ada percakapan</h2><p>{customerMode?'Percakapan dengan mitra akan muncul setelah Anda membuat pesanan.':'Percakapan customer akan muncul setelah ada pesanan untuk toko Anda.'}</p>{customerMode&&<Link className="btn primary" href="/jasa">Cari Jasa</Link>}</div>;
  return <div className={`chat-app card ${selected?'has-active':''}`}><aside className="chat-inbox"><div className="chat-inbox-title"><h1>Chat</h1></div><label className="chat-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari percakapan..."/></label><div className="chat-conversation-list">{filtered.map(c=><button key={c.orderId} className={selected===c.orderId?'active':''} onClick={()=>setSelected(c.orderId)}><span className="chat-avatar">{c.partnerLogo?<img src={c.partnerLogo} alt=""/>:<Store/>}</span><span className="chat-conversation-copy"><b>{c.partnerName}</b><small>#{c.orderId}</small><em>{c.lastMessage||'Belum ada pesan'}</em></span><time>{time(c.lastMessageAt)}</time>{c.lastMessageAt&&c.lastRole!==myRole&&(!c.readAt||new Date(c.lastMessageAt)>new Date(c.readAt))&&<i/>}</button>)}</div></aside><section className="chat-detail">{current?<><header><button className="chat-back" onClick={()=>setSelected('')} aria-label="Kembali"><ArrowLeft/></button><span className="chat-avatar">{current.partnerLogo?<img src={current.partnerLogo} alt=""/>:<Store/>}</span><div><b>{current.partnerName}</b><small>Order #{current.orderId}</small><em>{labels[status||current.status]||status||current.status}</em></div></header><div className="chat-messages">{hasOlder&&<button className="chat-load-older" type="button" onClick={loadOlder} disabled={loadingOlder}>{loadingOlder?'Memuat...':'Muat pesan sebelumnya'}</button>}{messages.map(m=>m.role==='SYSTEM'?<div className="chat-system" key={m.id}>{m.body}</div>:<div className={`message-row ${m.role===myRole?'mine':'theirs'}`} key={m.id}><div className="message-bubble"><p>{m.body}</p><time>{time(m.createdAt)}</time></div></div>)}<div ref={endRef}/></div>{error&&<div className="chat-error">{error}</div>}<form className="chat-composer" onSubmit={send}><input maxLength={2000} value={text} onChange={e=>setText(e.target.value)} placeholder="Ketik pesan..." aria-label="Pesan"/><button disabled={sending||!text.trim()} aria-label="Kirim"><Send/></button></form></>:<div className="chat-placeholder"><MessageCircle/><h2>Pilih percakapan</h2><p>Buka salah satu percakapan untuk melihat pesan.</p></div>}</section></div>
}
